#!/usr/bin/env bash
#transfer a file from a client to server

#PATH_TO_FILE="file_to_path"
#USERNAME="server_username"
#IP_ADDRESS="server_ip"
#DESTINATION="home_directory"

#scp -0 StrictHostKeyChecking=0 $PATH_TO_FILE $USERNAME@$IP_ADDRESS:$DESTINATION
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO-FILE IP USERNAME PATH_TO_SSH_KEY";
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi