#!/usr/bin/env bash

#installing nginx and configure it to remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo -i echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start