#!/usr/bin/env bash

#installing nginx and configure it to remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
chmod -r 777 /var
#cd /var/www/
#sudo chmod 777 html
echo 'Hello World!' > html/index.html
sudo chmod 755 html
cd ~
sudo service nginx restart 