#!/usr/bin/env bash
# Open the 80 port
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
