#!/usr/bin/env bash
# configure SSH client to connect to server without a password

Host server1
    HostName 44.200.168.88
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no