#!/usr/bin/env bash
# configure SSH client to connect to server without a password

Host server1
    HostName 44.210.107.96
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no